'usse client'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '../components/Providers'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pashva',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

        {children}
        <Toaster/>
        </Providers>
        </body>
    </html>
  )
}
